"""SessionStore protocol for structural typing."""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from janus.storage.session_store import RiskEvent, SessionState


@runtime_checkable
class SessionStore(Protocol):
    """Protocol that both InMemorySessionStore and PersistentSessionStore satisfy."""

    def get_or_create_session(self, session_id: str) -> SessionState: ...
    def get_risk_score(self, session_id: str) -> float: ...
    def set_risk_score(self, session_id: str, score: float) -> None: ...
    def add_event(self, session_id: str, event: RiskEvent) -> None: ...
    def get_events(self, session_id: str) -> list[RiskEvent]: ...
    def get_recent_events(self, session_id: str, window_seconds: float = 60.0) -> list[RiskEvent]: ...
    def record_tool_call(self, session_id: str, tool_name: str, tool_input: dict[str, object]) -> None: ...
    def get_tool_call_history(self, session_id: str) -> list[tuple[str, dict[str, object]]]: ...
    def set_goal(self, session_id: str, goal: str) -> None: ...
    def get_goal(self, session_id: str) -> str: ...
    def delete_session(self, session_id: str) -> None: ...
    def list_sessions(self) -> list[str]: ...
